version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo pre build config
      - cd website
      - yarn install
  build:
    commands:
      - echo build config
      - yarn build
      - ls build
  post_build:
    commands:
      - cd build
      - aws s3 sync --delete . "s3://network.o3.docs"
      - echo Build completed on `date`
